/**
 * YouTube Live Chat Collector - Runtime Environment Configuration
 * 
 * This file is generated by Terraform and provides runtime configuration
 * for the React.js application deployed on S3 Static Website.
 * 
 * Generated at: ${timestamp()}
 * Environment: ${environment}
 */

window.ENV_CONFIG = {
  // API Configuration
  API_BASE_URL: '${api_gateway_url}',
  API_KEY: '${api_key}',
  
  // Application Configuration
  APP_NAME: 'YouTube Live Chat Collector',
  APP_VERSION: '${app_version}',
  ENVIRONMENT: '${environment}',
  
  // Feature Flags
  DEBUG_MODE: ${environment == "dev" ? "true" : "false"},
  ENABLE_ANALYTICS: ${environment == "prod" ? "true" : "false"},
  
  // UI Configuration
  REFRESH_INTERVAL: 30000, // 30 seconds
  MAX_COMMENTS_PER_PAGE: 100,
  
  // AWS Region
  AWS_REGION: 'ap-northeast-1',
  
  // Deployment Information
  DEPLOYMENT_TIME: '${timestamp()}',
  TERRAFORM_MANAGED: true
};

// Make configuration available globally
if (typeof module !== 'undefined' && module.exports) {
  module.exports = window.ENV_CONFIG;
}

console.log('🚀 YouTube Live Chat Collector - Environment Configuration Loaded');
console.log('Environment:', window.ENV_CONFIG.ENVIRONMENT);
console.log('API Base URL:', window.ENV_CONFIG.API_BASE_URL);
console.log('Deployment Time:', window.ENV_CONFIG.DEPLOYMENT_TIME);
