---
# ECS Container Build and Deployment Playbook
- name: Deploy ECS Container
  hosts: localhost
  connection: local
  gather_facts: true
  
  vars:
    aws_region: "ap-northeast-1"
    aws_account_id: "209547544773"
    container_environment: "dev"
    cleanup_local_images: false
    
  tasks:
    - name: Deploy Comment Collector Container
      include_role:
        name: container-deployment
      vars:
        container_name: "comment-collector"
        container_source_dir: "../../src/ecs/comment_collector"
        ecr_repository_name: "dev-comment-collector"
        ecr_repository_uri: "209547544773.dkr.ecr.ap-northeast-1.amazonaws.com/dev-comment-collector"
        
    - name: Display deployment summary
      debug:
        msg: |
          🎉 Container deployment completed!
          
          📦 Container Details:
          - Name: dev-comment-collector
          - Tag: latest
          - ECR URI: 209547544773.dkr.ecr.ap-northeast-1.amazonaws.com/dev-comment-collector:latest
          
          🚀 Next Steps:
          1. Verify the image in ECR console
          2. Test ECS task execution
          3. Monitor CloudWatch logs
          
          💡 To run a test task:
          aws ecs run-task --cluster dev-youtube-comment-collector \
            --task-definition dev-comment-collector \
            --launch-type FARGATE \
            --network-configuration "awsvpcConfiguration={subnets=[subnet-xxx],securityGroups=[sg-xxx],assignPublicIp=ENABLED}"
