---
# API Handler Lambda専用デプロイプレイブック
- name: Deploy API Handler Lambda Function
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars:
    aws_region: "ap-northeast-1"
    env_name: "dev"
    
  tasks:
    - name: Deploy API Handler Lambda
      include_role:
        name: lambda-deployment
      vars:
        lambda_name: "api-handler-lambda"
        lambda_source_dir: "../../src/lambda/api_handler"
        lambda_environment: "{{ env_name }}"
