---
# ECS Task Launcher Lambda関数単体デプロイ用プレイブック
- name: Deploy ECS Task Launcher Lambda
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars:
    aws_region: "ap-northeast-1"
    env_name: "dev"
    
  tasks:
    - name: Deploy ECS Task Launcher Lambda
      include_role:
        name: lambda-deployment
      vars:
        lambda_name: "ecs-task-launcher-lambda"
        lambda_source_dir: "../../src/lambda/ecs_task_launcher"
        lambda_environment: "{{ env_name }}"
