---
# RSS Monitor Lambda関数単体デプロイ用プレイブック
- name: Deploy RSS Monitor Lambda
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars:
    aws_region: "ap-northeast-1"
    env_name: "dev"
    
  tasks:
    - name: Deploy RSS Monitor Lambda
      include_role:
        name: lambda-deployment
      vars:
        lambda_name: "rss-monitor-lambda"
        lambda_source_dir: "../../src/lambda/rss_monitor"
        lambda_environment: "{{ env_name }}"
