---
# Lambda関数デプロイ用プレイブック
- name: Deploy Lambda Functions
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars:
    aws_region: "ap-northeast-1"
    env_name: "dev"
    
  tasks:
    - name: Deploy RSS Monitor Lambda
      include_role:
        name: lambda-deployment
      vars:
        lambda_name: "rss-monitor-lambda"
        lambda_source_dir: "../../src/lambda/rss_monitor"
        lambda_environment: "{{ env_name }}"
        
    - name: Deploy Stream Status Checker Lambda
      include_role:
        name: lambda-deployment
      vars:
        lambda_name: "stream-status-checker-lambda"
        lambda_source_dir: "../../src/lambda/stream_status_checker"
        lambda_environment: "{{ env_name }}"
        
    - name: Deploy ECS Task Launcher Lambda
      include_role:
        name: lambda-deployment
      vars:
        lambda_name: "ecs-task-launcher-lambda"
        lambda_source_dir: "../../src/lambda/ecs_task_launcher"
        lambda_environment: "{{ env_name }}"
        
    - name: Deploy API Handler Lambda
      include_role:
        name: lambda-deployment
      vars:
        lambda_name: "api-handler-lambda"
        lambda_source_dir: "../../src/lambda/api_handler"
        lambda_environment: "{{ env_name }}"
